### ISSUE TITLE
Audio input stream question

### ISSUE THREAD

**Issue by rpryzant** [costomato/syncsrt#1]
Thanks for sharing this tool, it's super cool and I've used it a few times to sync subs :) 

I'm trying to extend your tool to create subtitles for the default mic input (continuous recognition) while also dumping the audio to a file. I noticed you implemented your own custom [audio stream](https://github.com/costomato/syncsrt/blob/main/helper.py#L9), and I was wondering if you have any ideas about how to accomplish this?

Was thinking maybe a custom audio stream like your [audio config](https://github.com/costomato/syncsrt/blob/33ad7130b46d78e0189c2b2956c2cda0d47afa43/main.py#L88) that intercepts the outgoing audio data and stream it to a file (while also sending to the ASR service), but do you know what kind of audio stream I would have to subclass, and might you know anything about how to intercept the audio, etc? 

Thanks a lot, looking forward to hearing your thoughts.

**Comment by costomato** [comment]
Hey there @rpryzant, thanks for reaching out! Yeah, so the custom audio stream and config that you are referring to are not written by me. I found the whole [helper.py](https://github.com/costomato/syncsrt/blob/33ad7130b46d78e0189c2b2956c2cda0d47afa43/helper.py) file on microsoft's website. I have not paid much attention to it, as the main aim of this tool is to synchronize an already existing subtitle file, based on the number of seconds mentioned by user.
But, I used azure's speech recognition to add another functionality to this application, i.e. to catch the starting timestamp from an audio file and synchronize a given subtitle file accordingly.
Hence, speech recognition and and timestamp detection are secondary purposes.
However, thank you so much for raising those questions. I'll do some research and look into it. Meanwhile, if you come up with a solution, then please do mention or make contributions! 😊

**Comment by rpryzant** [comment]
Gotcha, thanks for the detailed response!
